### ISSUE TITLE
GRAVE: server gets down when pressing cancel instead of entering name

### ISSUE THREAD

**Issue by micbuffa** [ALXRSS/WebRTC-Conf#50]
With the version at visio.gexsoft.com, I discovered that often the server was down. I digged into the logs + tried to reproduce the the crash. It occurs at the very beginning when the app prompts for entering a nickname. If I press "cancel" or just close the tab, the server crashes.

home/apps/webrtc/evry/WebRTC-Conf/Prototypes/one2many-current-version/node_modules/ent/index.js:7
        throw new TypeError('Expected a String');
              ^
TypeError: Expected a String
    at Object.exports.encode (/home/apps/webrtc/evry/WebRTC-Conf/Prototypes/one2many-current-version/node_modules/ent/index.js:7:15)
    at Socket.<anonymous> (/home/apps/webrtc/evry/WebRTC-Conf/Prototypes/one2many-current-version/server.js:73:22)
    at Socket.emit [as $emit](events.js:95:17)
    at SocketNamespace.handlePacket (/home/apps/webrtc/evry/WebRTC-Conf/Prototypes/one2many-current-version/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/apps/webrtc/evry/WebRTC-Conf/Prototypes/one2many-current-version/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/home/apps/webrtc/evry/WebRTC-Conf/Prototypes/one2many-current-version/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/home/apps/webrtc/evry/WebRTC-Conf/Prototypes/one2many-current-version/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)

Le 13 mars 2015 19:52, michel buffa micbuffa@gmail.com a écrit :
C'est reparti, je n'ai pas vu dans les logs pourquoi ça a planté...

Le 13 mars 2015 16:59, michel buffa micbuffa@gmail.com a écrit :

Ok je regarde ce soir

Le 13 mars 2015 12:54, "Didier COURTAUD" didier.courtaud@univ-evry.fr a écrit :
Me répond depuis 1/2 heure :

An error has occurred: {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}

**Comment by polskataga** [comment]
When the user enters a null pseudo or click on cancel, we generate a random pseudo to avoid that the server crashes.

We chose this rather than ask again a valid pseudo or allow a null pseudo.

**Comment by micbuffa** [comment]
If we click cancel that means that we do not want to enter. Ate you sure your solution covers this user case?

**Comment by polskataga** [comment]
Yes, if the user clicks on cancel, that means he does not want to enter a pseudo.

If he would want to exit, I think he just have to close his tab. So we do not have to expluse him if he clicks on cancel.

**Comment by micbuffa** [comment]
Ok but I don't understand how your algo works of you send a random pseudo
if he clicks cancel
